spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hiringgo_course
    username: postgres
    password: Hutajulu31
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
