spring:
  datasource:
    url: jdbc:postgresql://ep-odd-pine-a14f25f6-pooler.ap-southeast-1.aws.neon.tech/HiringGo%20Course?sslmode=require
    username: HiringGo Course_owner
    password: npg_jLtfN4hM2QEv
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
